# Generated by Django 4.2.2 on 2023-06-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('PRESIDENT', 'PRESIDENT'), ('VICE PRESIDENT', 'VICE PRESIDENT'), ('DIRECTOR OF SPORTS', 'DIRECTOR OF SPORTS'), ('STUDENT AFFAIRS', 'STUDENT AFFAIRS')], max_length=100)),
                ('photo', models.ImageField(upload_to='media/<django.db.models.fields.CharField>')),
                ('vote_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
