# Generated by Django 4.2.2 on 2023-06-16 17:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0004_alter_candidate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='media/candidates/'),
        ),
    ]
